dotenv: .env
compiler:
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.1"
          - "@envelop-protocol-v1=dao-envelop/envelop-protocol-v1@1.1.0"
dependencies:
    - dao-envelop/envelop-protocol-v1@1.1.0
